#!/bin/bash

# make CapsLock behave like Ctrl:
# NOTE: The command `setxkbmap -option ctrl:nocaps` was working initially but was
# getting undone after connecting a Bluetooth headset (???) whereas this
# command doesn't have that problem
gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"

# make short-pressed Ctrl behave like Escape:
xcape -e 'Control_L=Escape'
